name: CI - PR to develop

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Generate application-dev.yml
      run: |
        mkdir -p src/main/resources
        cat <<EOF > src/main/resources/application.yml
        server:
          port: 8080
        security:
          jwt:
            token:
              expire-length: ${{ secrets.JWT_EXPIRE_LENGTH }}
              secret-key: ${{ secrets.JWT_SECRET_KEY }}
        EOF

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
